name: Automatic Versioning

on:
  push:
    branches: [ 'master' ]

concurrency:
  group: versioning-master
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout PR history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: '${{ secrets.PAT_DEPLOYS }}'

      - name: Get branch prefix
        id: br_prefix
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=$(gh pr list --search "${{ github.sha }}" --state merged --json headRefName --jq '.[0].headRefName')
          echo "Merged branch: $BRANCH"

          if [[ -z "$BRANCH" || "$BRANCH" == "null" ]]; then
            echo "skip_version=true" >> $GITHUB_OUTPUT
            echo "Merge commit not found."
            exit 0
          fi

          if [[ "$BRANCH" == fix/* ]]; then
            echo "update_type=patch" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == feature/* ]]; then
            echo "update_type=minor" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == release/* ]]; then
            echo "update_type=major" >> $GITHUB_OUTPUT
          else
            echo "skip_version=true" >> $GITHUB_OUTPUT
            echo "Skipping version bump."
          fi

      - name: Setup Node.js
        if: steps.br_prefix.outputs.skip_version != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Update version in package.json
        if: steps.br_prefix.outputs.skip_version != 'true'
        id: update
        env:
          NPM_CONFIG_UNSAFE_PERM: true
        run: |
          UPDATE_TYPE="${{ steps.br_prefix.outputs.update_type }}"

          NEW_VERSION="$(npm version "$UPDATE_TYPE" --no-git-tag-version)"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version update
        if: steps.br_prefix.outputs.skip_version != 'true'
        run: |
          NEW_VERSION="${{ steps.update.outputs.version }}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add package.json package-lock.json

          if git diff --staged --quiet; then
            echo "No version changes to commit."
          else
            git commit -m "ci: update package version to ${NEW_VERSION} [skip ci]" || echo "Commit failed or no changes"
            git push origin master
          fi

      - name: Crate new tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.br_prefix.outputs.skip_version != 'true'
        run: |
          NEW_VERSION="${{ steps.update.outputs.version }}"

          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"
