name: Automatic Versioning

on:
  push:
    branches: [ 'master' ]

concurrency:
  group: versioning-master
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name from last merged PR
        id: pr_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BRANCH=$(gh api \
            repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
            --jq '.[0].head.ref')
          
          if [[ -z "$PR_BRANCH" ]]; then
            echo "Merge commit not found."
            exit 0
          fi                  
          
          echo "Merged branch: $PR_BRANCH" 
          echo "branch_name=$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Get branch prefix
        id: br_prefix
        run: |
          BRANCH="${{ steps.pr_info.outputs.branch_name }}"
          echo "Branch: $BRANCH"

          if [[ "$BRANCH" == fix/* ]]; then
            echo "update_type=patch" >> $GITHUB_OUTPUT            
          elif [[ "$BRANCH" == feature/* ]]; then
            echo "update_type=minor" >> $GITHUB_OUTPUT            
          elif [[ "$BRANCH" == release/* ]]; then
            echo "update_type=major" >> $GITHUB_OUTPUT            
          else
            echo "skip_version=true" >> $GITHUB_OUTPUT
            echo "Skipping version bumb."
          fi

      - name: Setup Node.js
        if: steps.br_prefix.outputs.skip_version != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Update version in package.json
        if: steps.br_prefix.outputs.skip_version != 'true'
        id: update
        env:
          NPM_CONFIG_UNSAFE_PERM: true
        run: |
          UPDATE_TYPE="${{ steps.br_prefix.outputs.update_type }}"
          echo "Update type: $UPDATE_TYPE"
          
          NEW_VERSION="$(npm version "$UPDATE_TYPE" --no-git-tag-version)"
          
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version is $NEW_VERSION"

      - name: Commit version update
        if: steps.br_prefix.outputs.skip_version != 'true'
        id: commit
        run: |
          NEW_VERSION="${{ steps.update.outputs.version }}"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add package.json 2>/dev/null || true
          
          if git diff --staged --quiet; then
            echo "No version changes to commit."
            
          else 
            git commit -m "ci: update package version to ${NEW_VERSION} [skip ci]" || echo "Commit failed or no changes"
            git push origin master
          fi

